### ISSUE TITLE
Allow Administrator to enter questions for student/mentor applications

### ISSUE THREAD

**Issue by shaolinhoward** [carrot-u/carrot-u-admin-app#79]
his requires a Rails controller which will display a form allowing the administrator to enter a question for the application. The administrator can select which application the question is for. They should also be able to mark existing questions as current/not current.

DB
```
  create_table "application_questions", force: :cascade do |t|
    t.text "text"
    t.string "role"
    t.boolean "current"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end
Acceptance criteria:
```

Allow admin to view a list of existing questions

Allow admin to create a new question

Allow admin to edit a selected question

Allow admin to delete a selected question

**Comment by muffy** [comment]
After working on this for a while trying to use the question-in-db strategy, I determined that it was not really consistent with how we do the applications. I implemented the student application with hard-coded questions, and I think we want to do the same with the mentor application.
